version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run dev 
    environment:
      - NODE_ENV=development

  
