version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run dev  
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
